apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: netflix-clone-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sanjananayak/netflix-clone-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          value: mongodb+srv://sanjanarawata1:wPpFMTwujsSvqaZu@cluster0.sdn2mxn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: netflix-clone-devops
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend
  type: LoadBalancer

