version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
    build:
      context: ./netflix-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./netflix-api:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./netflix-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./netflix-ui/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

volumes:
  data:
  logs: