apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: netflix-clone-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sanjananayak/netflix-clone-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://backend:5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: netflix-clone-devops
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
